spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/u-space?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: redis://localhost:6379 # Redis 连接地址，前缀为 redis://
          timeout: 3000

